<?php

namespace Database\Seeders;

use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class AtmPensionTypesSeeder extends Seeder
{
    public function run()
    {
        $data =
        [
            ['id' => 26, 'pension_name' => 'SSS-SD / EC / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 27, 'pension_name' => 'SSS-SD / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 28, 'pension_name' => 'SSS-SD / ITF1', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 29, 'pension_name' => 'SSS-SP', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 30, 'pension_name' => 'SSS-SP & SD', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 31, 'pension_name' => 'SSS-SP / EC', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 32, 'pension_name' => 'SSS-SP / EC / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 33, 'pension_name' => 'SSS-SP / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 34, 'pension_name' => 'SSS-ST', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 35, 'pension_name' => 'SSS-ST & SD', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 36, 'pension_name' => 'SSS-ST / EC', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 37, 'pension_name' => 'SSS-ST / EC / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 38, 'pension_name' => 'SSS-ST / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 39, 'pension_name' => 'SSS-RT & SD', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 40, 'pension_name' => 'SSS-RT / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 41, 'pension_name' => 'SSS-RT / SD', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 42, 'pension_name' => 'SSS-SD', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 43, 'pension_name' => 'SSS-SD / EC', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 44, 'pension_name' => 'SSS-SD / EC / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 45, 'pension_name' => 'SSS-SD / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 46, 'pension_name' => 'SSS-SD / ITF1', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 47, 'pension_name' => 'SSS-SP', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 48, 'pension_name' => 'SSS-SP & SD', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 49, 'pension_name' => 'SSS-SP / EC', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 50, 'pension_name' => 'SSS-RT', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 51, 'pension_name' => 'SSS-SD / EC / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 52, 'pension_name' => 'SSS-SD / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 53, 'pension_name' => 'SSS-SD / ITF1', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 54, 'pension_name' => 'SSS-SP', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 55, 'pension_name' => 'SSS-SP & SD', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 56, 'pension_name' => 'SSS-SP / EC', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 57, 'pension_name' => 'SSS-SP / EC / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 58, 'pension_name' => 'SSS-SP / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 59, 'pension_name' => 'SSS-ST', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 60, 'pension_name' => 'SSS-ST & SD', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 61, 'pension_name' => 'SSS-ST / EC', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 62, 'pension_name' => 'SSS-ST / EC / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 63, 'pension_name' => 'SSS-ST / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 64, 'pension_name' => 'SSS-RT & SD', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 65, 'pension_name' => 'SSS-RT / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 66, 'pension_name' => 'SSS-RT / SD', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 67, 'pension_name' => 'SSS-SD', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 68, 'pension_name' => 'SSS-SD / EC', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 69, 'pension_name' => 'SSS-SD / EC / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 70, 'pension_name' => 'SSS-SD / ITF', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 71, 'pension_name' => 'SSS-SD / ITF1', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 72, 'pension_name' => 'SSS-SP', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 73, 'pension_name' => 'SSS-SP & SD', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 74, 'pension_name' => 'SSS-SP / EC', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 75, 'pension_name' => 'SSS-RT', 'types' => 'SSS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 76, 'pension_name' => 'GSIS-SD / EC / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 77, 'pension_name' => 'GSIS-SD / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 78, 'pension_name' => 'GSIS-SD / ITF1', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 79, 'pension_name' => 'GSIS-SP', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 80, 'pension_name' => 'GSIS-SP & SD', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated _at' => Carbon::now()],
            ['id' => 81, 'pension_name' => 'GSIS-SP / EC', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 82, 'pension_name' => 'GSIS-SP / EC / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 83, 'pension_name' => 'GSIS-SP / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 84, 'pension_name' => 'GSIS-ST', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 85, 'pension_name' => 'GSIS-ST & SD', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 86, 'pension_name' => 'GSIS-ST / EC', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 87, 'pension_name' => 'GSIS-ST / EC / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 88, 'pension_name' => 'GSIS-ST / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 89, 'pension_name' => 'GSIS-RT & SD', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 90, 'pension_name' => 'GSIS-RT / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 91, 'pension_name' => 'GSIS-RT / SD', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 92, 'pension_name' => 'GSIS-SD', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 93, 'pension_name' => 'GSIS-SD / EC', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 94, 'pension_name' => 'GSIS-SD / EC / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 95, 'pension_name' => 'GSIS-SD / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 96, 'pension_name' => 'GSIS-SD / ITF1', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 97, 'pension_name' => 'GSIS-SP', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 98, 'pension_name' => 'GSIS-SP & SD', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 99, 'pension_name' => 'GSIS-SP / EC', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 100, 'pension_name' => 'GSIS-RT', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 101, 'pension_name' => 'GSIS-SD / EC / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 102, 'pension_name' => 'GSIS-SD / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 103, 'pension_name' => 'GSIS-SD / ITF1', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 104, 'pension_name' => 'GSIS-SP', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 105, 'pension_name' => 'GSIS-SP & SD', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 106, 'pension_name' => 'GSIS-SP / EC', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 107, 'pension_name' => 'GSIS-SP / EC / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 108, 'pension_name' => 'GSIS-SP / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 109, 'pension_name' => 'GSIS-ST', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 110, 'pension_name' => 'GSIS-ST & SD', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 111, 'pension_name' => 'GSIS-ST / EC', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 112, 'pension_name' => 'GSIS-ST / EC / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 113, 'pension_name' => 'GSIS-ST / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 114, 'pension_name' => 'GSIS-RT & SD', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 115, 'pension_name' => 'GSIS-RT / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 116, 'pension_name' => 'GSIS-RT / SD', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 117, 'pension_name' => 'GSIS-SD', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 118, 'pension_name' => 'GSIS-SD / EC', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 119, 'pension_name' => 'GSIS-SD / EC / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 120, 'pension_name' => 'GSIS-SD / ITF', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 121, 'pension_name' => 'GSIS-SD / ITF1', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 122, 'pension_name' => 'GSIS-SP', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 123, 'pension_name' => 'GSIS-SP & SD', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 124, 'pension_name' => 'GSIS-SP / EC', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 125, 'pension_name' => 'GSIS-RT', 'types' => 'GSIS', 'status' => 'Active', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]
        ];
        DB::table('data_pension_types_lists')->insert($data);
    }
}
