<?php

namespace Database\Seeders;

use Faker\Factory as Faker;
use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    public function run()
    {
        $faker = Faker::create();
            $data = [
                    [
                        'name' => 'Developer',
                        'employee_id' => '000001',
                        'email' => 'dev@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Developer',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 22,
                        'company_id' => 1,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],
                    [
                        'name' => 'Admin',
                        'employee_id' => '000002',
                        'email' => 'admin@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Admin',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 2,
                        'company_id' => 1,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],
                    [
                        'name' => 'Everfirst Admin',
                        'employee_id' => '000003',
                        'email' => 'everfirst_admin@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Admin',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 3,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Calderon HR',
                        'employee_id' => '000004',
                        'email' => 'calderonhr@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Admin',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 4,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Branch Head Admin',
                        'employee_id' => '000005',
                        'email' => 'samplebranchhead@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Branch',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 5,
                        'company_id' => 2,
                        'branch_id' => 5,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Area Supervisor Admin',
                        'employee_id' => '000007',
                        'email' => 'adminbranchareasupervisor@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Area',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 6,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Sample District Manager',
                        'employee_id' => '000008',
                        'email' => 'admindistrictmanager@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'District',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 7,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => 1,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Sample Verifier',
                        'employee_id' => '000009',
                        'email' => 'adminverifier@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'District',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 8,
                        'company_id' => 2,
                        'branch_id' => 5,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Rider Admin',
                        'employee_id' => '000010',
                        'email' => 'adminrider@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Branch',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 9,
                        'company_id' => 2,
                        'branch_id' => 5,
                        'district_code_id' => 1,
                        'area_code_id' => 1,
                    ],

                    [
                        'name' => 'Accounting Supervisor Admin',
                        'employee_id' => '000011',
                        'email' => 'accountingsupervisor@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 10,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Operations Manager Admin',
                        'employee_id' => '000012',
                        'email' => 'operationsmanager@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 11,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Treasury Head Admin',
                        'employee_id' => '000013',
                        'email' => 'treasuryhead@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 12,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Treasury Receiving Clerk Admin',
                        'employee_id' => '000014',
                        'email' => 'treasuryreceivingclerk@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 13,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Filling Clerk Admin',
                        'employee_id' => '000015',
                        'email' => 'fillingclerk@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 14,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Collection Receiving Clerk Admin',
                        'employee_id' => '000016',
                        'email' => 'collectionreceivingclerk@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 15,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Auditor Assistant Admin',
                        'employee_id' => '000017',
                        'email' => 'auditorassistant@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 16,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Auditor Assistant Admin',
                        'employee_id' => '000018',
                        'email' => 'treasuryassistantstaff@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 17,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Approving Officer Admin',
                        'employee_id' => '000019',
                        'email' => 'approvingofficer@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 18,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Accounting Staff Admin',
                        'employee_id' => '000020',
                        'email' => 'accountingstaff@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 19,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Collection Head Admin',
                        'employee_id' => '000021',
                        'email' => 'collectionhead@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 21,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'AP/AR Staff Admin',
                        'employee_id' => '000022',
                        'email' => 'aparstaff@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 25,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Payroll Clerk Admin',
                        'employee_id' => '000023',
                        'email' => 'payrollclerk@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 26,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Collection Department',
                        'employee_id' => '000024',
                        'email' => 'collectiondepartment@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 27,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Chief Accounting Admin',
                        'employee_id' => '000025',
                        'email' => 'chiefcccounting@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 28,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Warehouse Admin',
                        'employee_id' => '000026',
                        'email' => 'warehouse@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 29,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Accounting / Report Staff Admin',
                        'employee_id' => '000027',
                        'email' => 'accountingreportstaff@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 30,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Collection Staff Admin',
                        'employee_id' => '000028',
                        'email' => 'collectionstaff@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 31,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Collection Staff / Releasing Admin',
                        'employee_id' => '000029',
                        'email' => 'collectionstaffreleasing@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 32,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Finance Manager Admin',
                        'employee_id' => '000030',
                        'email' => 'financemanager@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 33,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Treasury Supervisor Admin',
                        'employee_id' => '000031',
                        'email' => 'treasurysupervisor@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 34,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Treasury Assistant Admin',
                        'employee_id' => '000032',
                        'email' => 'treasuryassistant@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 35,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Treasury Staff Admin',
                        'employee_id' => '000033',
                        'email' => 'treasurystaff@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 36,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Auditor Head Admin',
                        'employee_id' => '000034',
                        'email' => 'auditorhead@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 37,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Loan Processor Admin',
                        'employee_id' => '000035',
                        'email' => 'loanprocessor@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 38,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'General Accountant Admin',
                        'employee_id' => '000036',
                        'email' => 'generalaccountant@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 39,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Collection / Reports Staff Admin',
                        'employee_id' => '000037',
                        'email' => 'collectionreportsstaff@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 40,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Approving Head',
                        'employee_id' => '000038',
                        'email' => 'approvinghead@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 41,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'IT Staff Admin',
                        'employee_id' => '000039',
                        'email' => 'itstaff@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 42,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'HR Manager Admin',
                        'employee_id' => '000040',
                        'email' => 'hrmanager@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 43,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Purchasing Admin',
                        'employee_id' => '000041',
                        'email' => 'purchasing@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 44,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Treasury Rider',
                        'employee_id' => '000042',
                        'email' => 'treasuryrider@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 45,
                        'company_id' => 2,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Treasury (Multi-Line) Admin',
                        'employee_id' => '000043',
                        'email' => 'treasurymultiline@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 46,
                        'company_id' => 1,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Training Manager Admin',
                        'employee_id' => '000044',
                        'email' => 'trainingmanager@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 49,
                        'company_id' => 1,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Loan Consultant Admin',
                        'employee_id' => '000045',
                        'email' => 'loanconsultant@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 50,
                        'company_id' => 1,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Assistant Trainer Admin',
                        'employee_id' => '000046',
                        'email' => 'assistanttrainer@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 51,
                        'company_id' => 1,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Collection Custodian Admin',
                        'employee_id' => '000047',
                        'email' => 'collectioncustodian@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 52,
                        'company_id' => 1,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Collection Supervisor Admin',
                        'employee_id' => '000048',
                        'email' => 'collectionsupervisor@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 53,
                        'company_id' => 1,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Checker Admin',
                        'employee_id' => '000049',
                        'email' => 'checker@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 54,
                        'company_id' => 1,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

                    [
                        'name' => 'Passbook Custodian Admin',
                        'employee_id' => '000050',
                        'email' => 'passbookcustodian@gmail.com',
                        'password' => '$2y$12$Y0/wCO5ghJDL.DHsRaxOyOpByhTEv9z03pxZEcsKJjgh1JZL1Vn36',
                        'session' => 'Offline',
                        'user_types' => 'Head Office',
                        'email_verified_at' => Carbon::now(),
                        'dob' => Carbon::now(),
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now(),
                        'status' => 'Active',
                        'user_group_id' => 55,
                        'company_id' => 1,
                        'branch_id' => NULL,
                        'district_code_id' => NULL,
                        'area_code_id' => NULL,
                    ],

        ];
            DB::table('users')->insert($data);
    }
}
